/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Cadastro.Atualizar;
import Cadastro.Property;
import Cadastro.Salvar;
import Certificado.Export;
import XMLNotas.RelatorioXml;
import emisor.Find;
import java.awt.Cursor;
import java.io.*;
import java.io.FileInputStream;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import principal.Arquivos;
import principal.Buscar;

/**
 *
 * @author Qualidade
 */
public class PrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalGUI
     */
    public PrincipalGUI() {
        System.out.print(".");
        initComponents();
        //System.out.print(System.getProperty("user.dir"));
        fornecedor.getFornecedores();
        atualizar();
        System.out.print(".");
    }

    private void atualizar() {
        try {
            File file = new File("C:\\Emisor\\config.data");
            Properties pro = new Properties();
            pro.load(new FileInputStream(file));
            certificado.setText(pro.getProperty("numero"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visual = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tratamento = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        nCertificadoOriginal = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        norma = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        complemento = new javax.swing.JTextField();
        quantidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        unidadeQuantidade = new javax.swing.JLabel();
        descricaoProduto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nCertificadoTock = new javax.swing.JTextField();
        complementoDescricao = new javax.swing.JTextField();
        mensagem = new javax.swing.JLabel();
        Fornecedores = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nNota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campo4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        certificado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        v7 = new javax.swing.JTextField();
        q1 = new javax.swing.JTextField();
        q2 = new javax.swing.JTextField();
        q5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        v1 = new javax.swing.JTextField();
        v4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        q7 = new javax.swing.JTextField();
        q6 = new javax.swing.JTextField();
        v5 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        v6 = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        v3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        v14 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        v10 = new javax.swing.JTextField();
        q13 = new javax.swing.JTextField();
        v12 = new javax.swing.JTextField();
        v9 = new javax.swing.JTextField();
        q11 = new javax.swing.JTextField();
        q14 = new javax.swing.JTextField();
        q12 = new javax.swing.JTextField();
        v8 = new javax.swing.JTextField();
        v13 = new javax.swing.JTextField();
        q10 = new javax.swing.JTextField();
        q8 = new javax.swing.JTextField();
        q9 = new javax.swing.JTextField();
        v11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        f5 = new javax.swing.JTextField();
        vf3 = new javax.swing.JTextField();
        f6 = new javax.swing.JTextField();
        uf1 = new javax.swing.JTextField();
        f4 = new javax.swing.JTextField();
        vf1 = new javax.swing.JTextField();
        f7 = new javax.swing.JTextField();
        uf3 = new javax.swing.JTextField();
        vf2 = new javax.swing.JTextField();
        uf5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        uf6 = new javax.swing.JTextField();
        vf7 = new javax.swing.JTextField();
        vf5 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        vf4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        uf7 = new javax.swing.JTextField();
        f1 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        vf6 = new javax.swing.JTextField();
        uf2 = new javax.swing.JTextField();
        uf4 = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        nimbus = new javax.swing.JRadioButton();
        windows = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emisor de Certificado");
        setIconImage(new ImageIcon("C:\\Emisor\\icone2.png").getImage());
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tratamento.setMaximumRowCount(7);
        tratamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sem Tratamento", "Zincado Amarelo", "Zincado Branco", "Zincado Preto", "Zincado Fogo", "Polido", "Oxidado" }));
        tratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tratamentoActionPerformed(evt);
            }
        });
        jPanel1.add(tratamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 399, -1, -1));

        jButton4.setMnemonic('m');
        jButton4.setText("Imprimir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));
        jPanel1.add(nCertificadoOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 240, -1));

        jButton5.setMnemonic('c');
        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 500, -1, -1));

        jLabel9.setText("Tratamento: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 374, -1, -1));
        jPanel1.add(norma, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 90, -1));

        jButton3.setMnemonic('g');
        jButton3.setText("Gerar PDF");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, -1, -1));

        jLabel8.setText("Nº. Certificado Original: ");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));
        jPanel1.add(complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 399, 161, -1));
        jPanel1.add(quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 76, -1));

        jLabel7.setText("Norma");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 40, -1));
        jPanel1.add(unidadeQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 61, 20));
        jPanel1.add(descricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 438, -1));

        jLabel17.setText("Complemento:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 374, -1, -1));

        jLabel6.setText("Quantidade: ");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 76, -1));

        jLabel18.setText("Número Certificado:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 134, -1));

        nCertificadoTock.setEditable(false);
        nCertificadoTock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nCertificadoTockFocusLost(evt);
            }
        });
        jPanel1.add(nCertificadoTock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 462, 108, -1));
        jPanel1.add(complementoDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 399, 234, -1));

        mensagem.setBackground(new java.awt.Color(255, 0, 51));
        mensagem.setForeground(new java.awt.Color(255, 0, 51));
        mensagem.setToolTipText("");
        jPanel1.add(mensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 462, 97, 20));

        Fornecedores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FornecedoresItemStateChanged(evt);
            }
        });
        Fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FornecedoresActionPerformed(evt);
            }
        });
        jPanel1.add(Fornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 384, -1));

        jLabel1.setText("Cliente:");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel5.setText("Descrição: ");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 76, -1));
        jPanel1.add(nNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 101, -1));

        jLabel3.setText("Nº Nota:");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 57, -1));
        jPanel1.add(nPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 96, -1));

        jLabel2.setText("N.º Pedido:");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 74, -1));

        codProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codProdutoActionPerformed(evt);
            }
        });
        codProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codProdutoFocusLost(evt);
            }
        });
        jPanel1.add(codProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 191, -1));

        jLabel4.setText("Cod. Produto:");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel1.add(campo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 0, 337, 14));

        jProgressBar1.setValue(1);
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, -1, -1));
        jPanel1.add(certificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 462, 121, 20));

        jButton1.setMnemonic('a');
        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 500, -1, -1));

        jCheckBox1.setText("Atualizar Cadastro");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 140, -1));

        jLabel10.setText("Composição");

        jLabel11.setText("Valor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(q7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(v1)
                    .addComponent(v2)
                    .addComponent(v3)
                    .addComponent(v4)
                    .addComponent(v5)
                    .addComponent(v6)
                    .addComponent(v7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, -1));

        jLabel16.setText("Composição");

        jLabel15.setText("Valor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(q14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(v8)
                    .addComponent(v9)
                    .addComponent(v10)
                    .addComponent(v11)
                    .addComponent(v12)
                    .addComponent(v13)
                    .addComponent(v14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 103, -1, -1));

        uf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uf1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Valor");

        jLabel12.setText("Caracteristica");

        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });

        jLabel13.setText("Unidade");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(f1)
                    .addComponent(f2)
                    .addComponent(f3)
                    .addComponent(f4)
                    .addComponent(f5)
                    .addComponent(f6)
                    .addComponent(f7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uf1)
                    .addComponent(uf2)
                    .addComponent(uf3)
                    .addComponent(uf4)
                    .addComponent(uf5)
                    .addComponent(uf6)
                    .addComponent(uf7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vf1)
                    .addComponent(vf2)
                    .addComponent(vf3)
                    .addComponent(vf4)
                    .addComponent(vf5)
                    .addComponent(vf6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addComponent(vf7))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vf7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 103, 520, -1));

        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);

        nimbus.setText("Nimbus");
        nimbus.setEnabled(false);
        nimbus.setFocusable(false);
        nimbus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nimbus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        visual.add(nimbus);
        nimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimbusActionPerformed(evt);
            }
        });
        jToolBar1.add(nimbus);

        windows.setText("Windows");
        windows.setEnabled(false);
        windows.setFocusable(false);
        windows.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        windows.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        windows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowsActionPerformed(evt);
            }
        });
        visual.add(windows);
        jToolBar1.add(windows);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 110, -1));

        jMenu1.setMnemonic('f');
        jMenu1.setText("Ferramentas");

        jMenuItem1.setMnemonic('r');
        jMenuItem1.setText("Renomear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setMnemonic('a');
        jMenuItem2.setText("Atualizar Cadastros");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setMnemonic('o');
        jMenuItem3.setText("Notas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");

        jMenuItem4.setText("Sobre");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Thread ts = new Thread(new Property());
        ts.start();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.out.println("Iniciando..");
        System.out.println("Procurando em " + Arquivos.PASTATESTE.getPath());

        buscar.buscar(Arquivos.PASTATESTE);
        Thread busca = new Thread(buscar);
        busca.start();
        System.out.println("Terminou");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new RelatorioXml().criar();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Informar o codigo do produto.");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void codProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codProdutoFocusLost
        // TODO add your handling code here:
        Salvar arquivo = new Salvar(codProduto.getText());
        arquivo.carregar();
        dados[0] = certificado.getText();
        dados[1] = nPedido.getText();
        dados[2] = nNota.getText();
        dados[3] = fornecedor.getCNPJ(Fornecedores.getSelectedIndex());
        dados[4] = (String) Fornecedores.getSelectedItem();
        dados[5] = codProduto.getText();
        dados[6] = arquivo.getPropriedade("Descricao");
        dados[7] = " " + arquivo.getPropriedade("Unidade");
        dados[8] = arquivo.getPropriedade("Norma");
        dados[9] = arquivo.getPropriedade("Certificado");

        for (int i = 1; i < 15; i++) {
            dados[9 + i] = arquivo.getPropriedade("q" + i);
        }
        for (int i = 1; i < 15; i++) {
            dados[23 + i] = arquivo.getPropriedade("v" + i);
        }
        for (int i = 1; i < 8; i++) {
            dados[37 + i] = arquivo.getPropriedade("f" + i);
        }
        for (int i = 1; i < 8; i++) {
            dados[44 + i] = arquivo.getPropriedade("uf" + i);
        }
        for (int i = 1; i < 8; i++) {
            dados[51 + i] = arquivo.getPropriedade("vf" + i);
        }
        dados[59] = (String) tratamento.getSelectedItem();

        dados[60] = complemento.getText();

        dados[61] = complementoDescricao.getText();
        //descricaoProduto.setText();

        //unidadeQuantidade.setText(arquivo.getPropriedade("Unidade"));
        setCampos(dados);
        System.out.println(arquivo.getPropriedade("Descricao"));
    }//GEN-LAST:event_codProdutoFocusLost

    private void codProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codProdutoActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Informar o numero da ordem de compra do cliente.");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Informar o numero da nota fiscal.");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Informar a descricao do produto.");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Selecione o cliente.");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void FornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FornecedoresActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Informar a quantidade de produtos foi faturada na nfe.");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Informar a norma do produto, se ouver.");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, ".");
    }//GEN-LAST:event_jLabel8MouseClicked

    private void atualizarDados() {
        dados[0] = certificado.getText();
        dados[1] = nPedido.getText();
        dados[2] = nNota.getText();
        dados[3] = fornecedor.getCNPJ(Fornecedores.getSelectedIndex());
        dados[4] = (String) Fornecedores.getSelectedItem();
        dados[5] = codProduto.getText();
        dados[6] = descricaoProduto.getText();
        dados[7] = quantidade.getText() + " " + unidadeQuantidade.getText();
        dados[8] = norma.getText();
        dados[9] = nCertificadoOriginal.getText();

        dados[10] = q1.getText();
        dados[11] = q2.getText();
        dados[12] = q3.getText();
        dados[13] = q4.getText();
        dados[14] = q5.getText();
        dados[15] = q6.getText();
        dados[16] = q7.getText();
        dados[17] = q8.getText();
        dados[18] = q9.getText();
        dados[19] = q10.getText();
        dados[20] = q11.getText();
        dados[21] = q12.getText();
        dados[22] = q13.getText();
        dados[23] = q14.getText();

        dados[24] = v1.getText();
        dados[25] = v2.getText();
        dados[26] = v3.getText();
        dados[27] = v4.getText();
        dados[28] = v5.getText();
        dados[29] = v6.getText();
        dados[30] = v7.getText();
        dados[31] = v8.getText();
        dados[32] = v9.getText();
        dados[33] = v10.getText();
        dados[34] = v11.getText();
        dados[35] = v12.getText();
        dados[36] = v13.getText();
        dados[37] = v14.getText();

        dados[38] = f1.getText();
        dados[39] = f2.getText();
        dados[40] = f3.getText();
        dados[41] = f4.getText();
        dados[42] = f5.getText();
        dados[43] = f6.getText();
        dados[44] = f7.getText();

        dados[45] = uf1.getText();
        dados[46] = uf2.getText();
        dados[47] = uf3.getText();
        dados[48] = uf4.getText();
        dados[49] = uf5.getText();
        dados[50] = uf6.getText();
        dados[51] = uf7.getText();

        dados[52] = vf1.getText();
        dados[53] = vf2.getText();
        dados[54] = vf3.getText();
        dados[55] = vf4.getText();
        dados[56] = vf5.getText();
        dados[57] = vf6.getText();
        dados[58] = vf7.getText();

        dados[59] = (String) tratamento.getSelectedItem();

        dados[60] = complemento.getText();

        dados[61] = complementoDescricao.getText();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // implementar
        //String[] dados = new String[62];
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        atualizarDados();
        if(jCheckBox1.isSelected()){
            Atualizar.Atualizar(dados);            
        }
        progresso(20);

        cert.setDados(dados);
        cert.gerarNumero();
        cert.salvar();

        progresso(0);
        atualizar();
        setCursor(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void setCampos(String[] dado) {
        certificado.setText(dado[0]);

        nPedido.setText(dado[1]);
        nNota.setText(dado[2]);
        campo4.setText(dado[3]);
        Fornecedores.setSelectedItem(dado[4]);

        codProduto.setText(dado[5]);
        descricaoProduto.setText(dado[6]);
        quantidade.setText(dado[7].split(" ")[0]);
        unidadeQuantidade.setText(dado[7].split(" ")[1]);
        norma.setText(dado[8]);
        nCertificadoOriginal.setText(dado[9]);

        q1.setText(dado[10]);
        q2.setText(dado[11]);
        q3.setText(dado[12]);
        q4.setText(dado[13]);
        q5.setText(dado[14]);
        q6.setText(dado[15]);
        q7.setText(dado[16]);
        q8.setText(dado[17]);
        q9.setText(dado[18]);
        q10.setText(dado[19]);
        q11.setText(dado[20]);
        q12.setText(dado[21]);
        q13.setText(dado[22]);
        q14.setText(dado[23]);

        v1.setText(dado[24]);
        v2.setText(dado[25]);
        v3.setText(dado[26]);
        v4.setText(dado[27]);
        v5.setText(dado[28]);
        v6.setText(dado[29]);
        v7.setText(dado[30]);
        v8.setText(dado[31]);
        v9.setText(dado[32]);
        v10.setText(dado[33]);
        v11.setText(dado[34]);
        v12.setText(dado[35]);
        v13.setText(dado[36]);
        v14.setText(dado[37]);

        f1.setText(dado[38]);
        f2.setText(dado[39]);
        f3.setText(dado[40]);
        f4.setText(dado[41]);
        f5.setText(dado[42]);
        f6.setText(dado[43]);
        f7.setText(dado[44]);
        uf1.setText(dado[45]);
        uf2.setText(dado[46]);
        uf3.setText(dado[47]);
        uf4.setText(dado[48]);
        uf5.setText(dado[49]);
        uf6.setText(dado[50]);
        uf7.setText(dado[51]);
        vf1.setText(dado[52]);
        vf2.setText(dado[53]);
        vf3.setText(dado[54]);
        vf4.setText(dado[55]);
        vf5.setText(dado[56]);
        vf6.setText(dado[57]);
        vf7.setText(dado[58]);

        tratamento.setSelectedItem(dado[59]);

        complemento.setText(dado[60]);

        complementoDescricao.setText(dado[61]);
    }

    public static void progresso(int i) {
        
        jProgressBar1.setValue(i);
        jProgressBar1.updateUI();
        
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.nCertificadoTock.setEditable(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f3ActionPerformed

    private void uf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uf1ActionPerformed

    private void FornecedoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FornecedoresItemStateChanged
        // TODO add your handling code here:
        campo4.setText(fornecedor.getCNPJ(Fornecedores.getSelectedIndex()));
    }//GEN-LAST:event_FornecedoresItemStateChanged

    private void tratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tratamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tratamentoActionPerformed

    private void nCertificadoTockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nCertificadoTockFocusLost
        // TODO add your handling code here:
        nCertificadoTock.setEditable(false);
        try {
            File certi = Find.procurarTxt(nCertificadoTock.getText());
            BufferedReader cert = new BufferedReader(new FileReader(certi));
            String linha = null;
            int i = 0;
            while ((linha = cert.readLine()) != null) {
                dados[i] = linha;
                i++;
            }

            setCampos(dados);

            mensagem.setText("");
        } catch (Exception e) {
            mensagem.setText("Nao encontrado");
        }
    }//GEN-LAST:event_nCertificadoTockFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Export.imprimir(certificado.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        progresso(1);
        atualizarDados();
        progresso(5);
        if(jCheckBox1.isSelected()){
            Atualizar.Atualizar(dados);
        }
        
        progresso(10);
        cert.setDados(dados);
        progresso(15);
        cert.salvar();
        progresso(100);
        
        setCursor(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void windowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowsActionPerformed
        // TODO add your handling code here:
        if(windows.isSelected()){
            try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    SwingUtilities.updateComponentTreeUI(this);
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_windowsActionPerformed

    private void nimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimbusActionPerformed
        // TODO add your handling code here:
        if(nimbus.isSelected()){
            try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    SwingUtilities.updateComponentTreeUI(this);
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_nimbusActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Versao: " + Sobre.getVersao() + "\nAutor:"+ Sobre.getAutor() + "\n" + Sobre.getFrase());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.out.print("Iniciando.");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        System.out.print(".");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.print(".");
                new PrincipalGUI().setVisible(true);
                System.out.print("\nIniciou");
            }
        });
    }

    public Fornecedores fornecedor = new Fornecedores();
    private static Buscar buscar = new Buscar();
    private String[] dados = new String[62];
    private Certificado cert = new Certificado(dados);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox Fornecedores;
    private javax.swing.JLabel campo4;
    private javax.swing.JLabel certificado;
    private javax.swing.JTextField codProduto;
    private javax.swing.JTextField complemento;
    private javax.swing.JTextField complementoDescricao;
    private javax.swing.JTextField descricaoProduto;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JTextField f5;
    private javax.swing.JTextField f6;
    private javax.swing.JTextField f7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel mensagem;
    private javax.swing.JTextField nCertificadoOriginal;
    private javax.swing.JTextField nCertificadoTock;
    private javax.swing.JTextField nNota;
    private javax.swing.JTextField nPedido;
    private javax.swing.JRadioButton nimbus;
    private javax.swing.JTextField norma;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q10;
    private javax.swing.JTextField q11;
    private javax.swing.JTextField q12;
    private javax.swing.JTextField q13;
    private javax.swing.JTextField q14;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q5;
    private javax.swing.JTextField q6;
    private javax.swing.JTextField q7;
    private javax.swing.JTextField q8;
    private javax.swing.JTextField q9;
    private javax.swing.JTextField quantidade;
    private javax.swing.JComboBox tratamento;
    private javax.swing.JTextField uf1;
    private javax.swing.JTextField uf2;
    private javax.swing.JTextField uf3;
    private javax.swing.JTextField uf4;
    private javax.swing.JTextField uf5;
    private javax.swing.JTextField uf6;
    private javax.swing.JTextField uf7;
    private javax.swing.JLabel unidadeQuantidade;
    private javax.swing.JTextField v1;
    private javax.swing.JTextField v10;
    private javax.swing.JTextField v11;
    private javax.swing.JTextField v12;
    private javax.swing.JTextField v13;
    private javax.swing.JTextField v14;
    private javax.swing.JTextField v2;
    private javax.swing.JTextField v3;
    private javax.swing.JTextField v4;
    private javax.swing.JTextField v5;
    private javax.swing.JTextField v6;
    private javax.swing.JTextField v7;
    private javax.swing.JTextField v8;
    private javax.swing.JTextField v9;
    private javax.swing.JTextField vf1;
    private javax.swing.JTextField vf2;
    private javax.swing.JTextField vf3;
    private javax.swing.JTextField vf4;
    private javax.swing.JTextField vf5;
    private javax.swing.JTextField vf6;
    private javax.swing.JTextField vf7;
    private javax.swing.ButtonGroup visual;
    private javax.swing.JRadioButton windows;
    // End of variables declaration//GEN-END:variables
}
